remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: "Vronicle: Verifiable Provenance for Videos from Mobile Devices"
name: "Vronicle: Verifiable Provenance for Videos from Mobile Devices"
show_downloads: true
